title: Site

tabs:
  content:
    label: Content
    icon: 📚
    sections:
      content_tab:
        type: pages
        status: listed
        headline: Subpages
        layout: cards
        image:
          ratio: 3/2
          cover: true
        info: "{{ page.children.count }}"

      hello:
        type: pages
        status: unlisted
        headline: Unlisted Pages
        templates:
          - reviews
          - features
          - opinions
          - interviews
        info: "{{ page.children.count }}"

  site:
    label: Everything else
    icon: 🔍
    sections:
      ee_tab:
        type: pages
        templates:
          - about
          - blank
