title: Site

tabs:
  content:
    label: Content
    icon: 📚
    sections:
      content_tab:
        type: pages
        status: listed
        headline: Subpages
        layout: cards
        image:
          ratio: 3/2
          cover: true
        info: "{{ page.children.count }}"
  site:
    label: Everything else
    icon: 🔍
    sections:
      ee_tab:
        type: pages
        templates:
          - about
          - blank

  stats:
    label: Stats
    icon: 📊
    sections:
      stats_tab:
      fields:
        text:
          type: text
